# NumPy Notebook 4: Math & Broadcasting
"Doing magic with array calculations!"



## What You'll Learn  
1. **Universal Functions**: Fast math on arrays  
2. **Broadcasting**: Math between different shapes  
3. **Statistics**: Mean, median, standard deviation  
4. **Real Use**: Analyzing exam scores  

## Universal Functions (ufuncs)  
Fast math operations that work on **entire arrays** at once.  

Common ufuncs:  
- `np.add()`, `np.subtract()`  
- `np.sin()`, `np.log()`  
- `np.isnan()`  

In [1]:
import numpy as np

angles = np.array([0, 30, 45, 90])
radians = np.deg2rad(angles)  # Convert to radians
print("Sines:", np.sin(radians))  # [0. , 0.5, 0.707, 1. ]

# Calculate 2^x for all x
powers = np.array([1, 2, 3])
print("2^pows:", 2 ** powers)  # [2, 4, 8]

Sines: [0.         0.5        0.70710678 1.        ]
2^pows: [2 4 8]


## Broadcasting Rules  
NumPy can do math between arrays of **different shapes** if:  
1. Their dimensions match, or  
2. One has size 1 in a dimension  

Think of it like stretching smaller arrays to fit!

In [2]:
# Adding scalar to array (stretched automatically)
arr = np.array([1, 2, 3])
print("Add 5:", arr + 5)  # [6, 7, 8]

# 2D + 1D
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
print("Matrix + Vector:\n", matrix + vector)  # [[11,22],[13,24]]

Add 5: [6 7 8]
Matrix + Vector:
 [[11 22]
 [13 24]]


## Image Brightness Adjustment  
Broadcasting shines in real tasks like image processing!

In [3]:
# Simulate 3x3 grayscale image (0=black, 255=white)
image = np.array([
    [50, 100, 150],
    [200, 50, 100],
    [50, 200, 50]
])

# Increase brightness by 50 (applies to all pixels)
brighter = np.clip(image + 50, 0, 255)  # Clip to valid range
print("Brighter image:\n", brighter)

Brighter image:
 [[100 150 200]
 [250 100 150]
 [100 250 100]]


## Basic Statistics  
Essential for data analysis!

In [4]:
scores = np.array([88, 72, 95, 60, 100])

print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("Standard Dev:", np.std(scores))
print("Max score:", scores.max())

# Axis-based stats for 2D
data = np.array([[1, 2], [3, 4]])
print("Column means:", np.mean(data, axis=0))  # [2., 3.]

Mean: 83.0
Median: 88.0
Standard Dev: 14.886235252742717
Max score: 100
Column means: [2. 3.]


## Temperature Analysis  
Calculate daily stats from sensor data  

In [6]:
# Simulate weekly temps (7 days, 24 hours)
temps = np.random.randint(15, 35, (7, 24))
print(temps)
print("Weekly avg:", np.mean(temps))
print("Daily highs:", temps.max(axis=1))  # Max per day
print("Hourly avgs:", temps.mean(axis=0))  # Avg per hour

[[17 23 34 30 28 31 29 26 20 29 27 21 17 16 26 29 25 19 26 32 32 32 27 23]
 [17 26 26 30 34 24 32 33 23 33 23 31 30 18 18 31 18 29 24 32 19 29 32 17]
 [31 19 20 19 34 27 19 25 29 24 29 30 21 22 33 17 16 33 32 16 20 20 30 15]
 [15 15 32 17 28 23 25 20 30 27 19 19 25 25 32 16 21 16 24 18 32 19 17 15]
 [16 26 18 30 26 30 33 19 27 16 23 30 24 21 18 20 27 33 19 30 23 16 15 33]
 [30 31 29 25 17 21 29 31 22 34 32 30 34 22 16 22 21 28 28 20 24 16 24 18]
 [19 18 17 33 19 18 19 17 21 18 15 33 20 18 26 24 21 22 21 30 27 15 21 18]]
Weekly avg: 24.083333333333332
Daily highs: [34 34 34 32 33 34 33]
Hourly avgs: [20.71428571 22.57142857 25.14285714 26.28571429 26.57142857 24.85714286
 26.57142857 24.42857143 24.57142857 25.85714286 24.         27.71428571
 24.42857143 20.28571429 24.14285714 22.71428571 21.28571429 25.71428571
 24.85714286 25.42857143 25.28571429 21.         23.71428571 19.85714286]


## Practice Time!  
1. Create 3x3 array and subtract 5 from all values  
2. Calculate row-wise means for a 2D array  
3. Multiply a 3x1 array by a 1x3 array using broadcasting  
4. Find days where max temp > 30°C (from Cell 6)  

*(Solutions in next cell)*  

In [7]:
# 1
arr = np.arange(1, 10).reshape(3, 3)
print("Subtracted:\n", arr - 5)

# 2
print("Row means:", arr.mean(axis=1))

# 3
a = np.array([[1], [2], [3]])  # 3x1
b = np.array([10, 20, 30])     # 1x3
print("Broadcast multiply:\n", a * b)  # 3x3 result

# 4 (using temps from Cell 6)
print("Hot days:", np.where(temps.max(axis=1) > 30)[0])

Subtracted:
 [[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
Row means: [2. 5. 8.]
Broadcast multiply:
 [[10 20 30]
 [20 40 60]
 [30 60 90]]
Hot days: [0 1 2 3 4 5 6]
