# NumPy Notebook 2: Array Shapes & Sizes
"Like Lego blocks for numbers!"

## Why Shapes Matter?  
Arrays can be:  
- **1D**: A line of numbers (like a shopping list)  
- **2D**: A grid (like Excel sheet)  
- **3D+**: A cube or higher (like MRI scan layers)  

 **Real-World Use**:  
- 1D: Temperature readings  
- 2D: Black-and-white images  
- 3D: Color images (RGB layers)  

In [1]:
import numpy as np

# 1D array (vector)
groceries = np.array(["🍎", "🥛", "🍞"])
print("Groceries shape:", groceries.shape)  # (3,) → 3 items

# 2D array (matrix)
chessboard = np.array([
    ["♜", "♞", "♝"],
    ["♚", "♛", "♝"]
])
print("Chessboard shape:", chessboard.shape)  # (2, 3) → 2 rows, 3 columns

Groceries shape: (3,)
Chessboard shape: (2, 3)


## Reshaping Arrays  
Turn a line of numbers into a grid!  
*Rule: Total elements must stay the same.*  

In [2]:
# From 1D to 2D
numbers = np.arange(1, 7)  # [1, 2, 3, 4, 5, 6]
grid = numbers.reshape(2, 3)  # 2 rows, 3 cols
print("Reshaped grid:\n", grid)

# Common error (will crash!)
try:
    bad_grid = numbers.reshape(3, 3)  # Needs 9 elements!
except ValueError as e:
    print("Error:", e)

Reshaped grid:
 [[1 2 3]
 [4 5 6]]
Error: cannot reshape array of size 6 into shape (3,3)


## Stacking Arrays  
Combine arrays like Lego blocks:  
- `vstack`: Vertical (row-wise)  
- `hstack`: Horizontal (column-wise)  

In [3]:
# Stack two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical stack:\n", np.vstack((a, b)))  # 2 rows
print("Horizontal stack:", np.hstack((a, b)))  # 1 long row

Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


## Flattening Arrays  
Turn any array back to 1D:  
- `.flatten()`: Makes a copy  
- `.ravel()`: Uses original memory  

In [4]:
grid = np.array([[1, 2], [3, 4]])

flattened = grid.flatten()
raveled = grid.ravel()

print("Flattened:", flattened)  # [1, 2, 3, 4]
print("Raveled:", raveled)      # Same output

Flattened: [1 2 3 4]
Raveled: [1 2 3 4]


## Image Processing Demo  
Black-and-white images = 2D arrays!

In [5]:
# Simulate a tiny 3x3 pixel image
image = np.array([
    [0, 255, 0],  # Black, White, Black
    [255, 0, 255],
    [0, 255, 0]
])

# Flip the image vertically
flipped = np.vstack((image[2], image[1], image[0]))
print("Flipped image:\n", flipped)

Flipped image:
 [[  0 255   0]
 [255   0 255]
 [  0 255   0]]


## Practice Time!  
1. Create a 1D array with 8 numbers  
2. Reshape it into 2x4 and 4x2 grids  
3. Stack two 2x2 arrays vertically  
4. Flatten the result  

*(Solutions in next cell)*  

In [6]:
# 1-2
arr = np.arange(1, 9)
print("2x4:\n", arr.reshape(2, 4))
print("4x2:\n", arr.reshape(4, 2))

# 3-4
a = np.array([[1, 2], [3, 4]])
stacked = np.vstack((a, a))
print("Stacked:\n", stacked)
print("Flattened:", stacked.flatten())

2x4:
 [[1 2 3 4]
 [5 6 7 8]]
4x2:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stacked:
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]
Flattened: [1 2 3 4 1 2 3 4]
